server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          uri: https://github.com/michaelkimm/spring-cloud-config.git
          default-label: master
#          uri: file://C:\Users\alstj\Desktop\Github\git-local-repo

management:
  endpoint:
    web:
      exposure:
        include: health, busrefresh