server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/michaelkimm/spring-cloud-config.git
#          uri: file://C:\Users\alstj\Desktop\Github\git-local-repo